version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_DB: api_development
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: 
      context: .
      target: dev
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=debug
    volumes:
      - ./:/go/src/app

volumes:
  pg_data: